# Generated by Django 5.1.6 on 2025-02-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
    ]
