# Generated by Django 5.1.6 on 2025-02-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_password1_user_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
