# Generated by Django 5.1.6 on 2025-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_rename_question_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(max_length=90),
        ),
    ]
