# Generated by Django 5.1.6 on 2025-02-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_alter_question_user_alter_tag_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tags',
            new_name='tag',
        ),
    ]
