# Generated by Django 5.1.6 on 2025-02-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_rename_tags_question_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tag',
            new_name='tags',
        ),
    ]
