# Generated by Django 5.1.6 on 2025-02-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_rename_tag_question_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
