# Generated by Django 5.1.6 on 2025-02-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_rename_tags_question_tag_rename_tag_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(related_name='t', to='question.tag'),
        ),
    ]
